# Generated by Django 5.1.5 on 2025-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='path_badge',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='path_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='path_qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='qr_codes/'),
        ),
    ]
