# Generated by Django 5.1.5 on 2025-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0002_alter_user_path_badge_alter_user_path_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_data',
            field=models.TextField(default=''),
        ),
    ]
